DROP DATABASE IF EXISTS sakaki;
CREATE DATABASE sakaki;
GRANT ALL ON sakaki.* TO sakaki@'%' IDENTIFIED BY 'sakaki';
USE sakaki;
CREATE TABLE posts (
  post_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title TEXT,
  content TEXT NOT NULL,
  board TEXT NOT NULL,
  is_op BOOLEAN NOT NULL,
  parent INTEGER,
  date_posted DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  bump_date DATETIME DEFAULT CURRENT_TIMESTAMP,
);
